adminconsole/Controllers/LocationsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using adminconsole.Models;
using adminconsole.Backend;
using DatabaseLibrary.Models;
using System;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Collections.Generic;

namespace adminconsole.Controllers
{
    public class LocationsController : Controller
    {

        private readonly MaphawksContext _context;
        private LocationsBackend backend;


        /// <summary>
        /// Constructor for normal function of application
        /// </summary>
        /// <param name="context"></param>
        public LocationsController(MaphawksContext context, LocationsBackend backend=null)
        {
            _context = context;

            // Fork to allow for mocking out backend
            if (backend != null)
            {
                this.backend = backend;
            } else
            {
                this.backend = new LocationsBackend(_context);
            }
        }


        /// GET:
        /// <summary>Locations objects with joins on Contacts, SpecialQualities, and DailyHours.</summary>
        /// 
        /// <returns> Index View with injected list of Locations objects </returns>
        public async Task<IActionResult> Index(string searchKeyword)
        {
            var results = await backend.GetRangeOfRecords(0, 500);
            
            //var results = await backend.IndexAsync().ConfigureAwait(false);
            //results = results.GetRange(0, 3);
            return View(results);

        }


        /// POST: 
        /// <summary>Searches database for a keyword in the Name, Address, City, or State fields.</summary>
        /// 
        /// <param name="SearchKeyword"> Search keyword or phrase </param>
        /// 
        /// <returns> Redirects to Index if an error, otherwise returns the Search view </returns>
        [HttpPost]
        public ActionResult Search(string SearchKeyword)
        {

            if (string.IsNullOrEmpty(SearchKeyword) ||
                string.IsNullOrWhiteSpace(SearchKeyword))
            {
                return RedirectToAction(nameof(Index));
            }
            var results = _context.Locations
                                .Include(c => c.Contact)
                                .Include(s => s.SpecialQualities)
                                .Include(d => d.DailyHours)
                                .Where(record => record.Name.Contains(SearchKeyword) || record.Address.Contains(SearchKeyword) || record.City.Contains(SearchKeyword) || record.State.Contains(SearchKeyword))
                                .Where(record => record.SoftDelete == false)
                                .ToList();
            return View(results);
        }


        /// POST: 
        /// <summary> Endpoint for Ajax pagin call.</summary>
        /// 
        /// <param name="start_index"> Defines how many records to Skip() </param>
        /// <param name="num_records"> Defines how many records to Take() </param>
        /// 
        /// <returns> Returns records as an HTML string to insert if there are more records, otherwise returns an empty string </returns>
        [HttpPost]
        [Produces("application/json")]
        public async Task<JsonResult> GetRangeOfRecords(int start_index, int num_records)
        {
            string error_msg = null;
            if (start_index < 0)
            {
                error_msg = "Start index cannot be less than 0. Your start index was: " + start_index;
            }

            if (num_records < 1)
            {
                error_msg = "Number of records cannot be less than 1. Your number of records was: " + num_records;
            }

            if (!string.IsNullOrEmpty(error_msg))
            {
                var ret =  new JsonResult(error_msg);
                return ret;
            }

            var result_list = await backend.GetRangeOfRecords(start_index, num_records);

            var result_html = backend.CreateTableRow(result_list, start_index);


            var response = new JsonResult(new
            {
                html = result_html,
                number_records = result_list.Count
            });

            return response;

        }


        /// GET: Locations/Details/5
        /// <summary>Singular Locations object joined with Contacts, SpecialQualities, and DailyHours.</summary>
        ///
        /// <returns> Details View with injected list of Locations objects </returns>
        public async Task<IActionResult> Details(string id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var result = await backend.DetailsAsync(id).ConfigureAwait(false);

            if (result == null)
            {
                return NotFound();
            }

            return View(result);

        }


        /// GET: Locations/Create
        /// <summary>Displays the Create View with the intent of inserting into the Database.</summary>
        /// 
        /// <returns> Create View </returns>
        public IActionResult Create()
        {
            return View();
        }



        /// POST: 
        /// <summary>Receives a LocationsContactsSpecialQualitiesViewModel Object with the intent of inserting into the Database.</summary>
        /// 
        /// <param name="newLocation"> LocationsContactsSpecialQualitiesViewModel Object, instantiated with values provided by the user </param>
        /// 
        /// <returns> Either returns the existing view if there is an error, otherwise returns the Index View </returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("LocationId," +
            "CoopLocationId," +
            "TakeCoopData," +
            "SoftDelete," +
            "Name," +
            "Address," +
            "City," +
            "County," +
            "State," +
            "PostalCode," +
            "Country," +
            "Latitude," +
            "Longitude," +
            "Hours," +
            "RetailOutlet," +
            "LocationType," +
            "Phone," +
            "Fax," +
            "WebAddress," +
            "RestrictedAccess," +
            "AcceptDeposit," +
            "AcceptCash," +
            "EnvelopeRequired," +
            "OnMilitaryBase," +
            "OnPremise," +
            "Surcharge," +
            "Access," +
            "AccessNotes," +
            "InstallationType," +
            "HandicapAccess," +
            "Cashless," +
            "DriveThruOnly," +
            "LimitedTransactions," +
            "MilitaryIdRequired," +
            "SelfServiceDevice," +
            "SelfServiceOnly," +
            "HoursMonOpen," +
            "HoursMonClose," +
            "HoursTueOpen," +
            "HoursTueClose," +
            "HoursWedOpen," +
            "HoursWedClose," +
            "HoursThuOpen," +
            "HoursThuClose," +
            "HoursFriOpen," +
            "HoursFriClose," +
            "HoursSatOpen," +
            "HoursSatClose," +
            "HoursSunOpen," +
            "HoursSunClose," +
            "HoursDtmonOpen," +
            "HoursDtmonClose," +
            "HoursDttueOpen," +
            "HoursDttueClose," +
            "HoursDtwedOpen," +
            "HoursDtwedClose," +
            "HoursDtthuOpen," +
            "HoursDtthuClose," +
            "HoursDtfriOpen," +
            "HoursDtfriClose," +
            "HoursDtsatOpen," +
            "HoursDtsatClose," +
            "HoursDtsunOpen," +
            "HoursDtsunClose")] AllTablesViewModel newLocation)
        {

            if (!ModelState.IsValid)
            {
                var view = View(newLocation);
                view.ViewName = "Create";
                return view;
            }


            var result = backend.Create(newLocation);


            return RedirectToAction(nameof(Index));

        }


        /// GET: Locations/Edit/5
        /// <summary>Allows the user to edit the Location information of a given Locations Object.</summary>
        ///
        /// <param name="id"> string ID of the Locations Object </param>
        /// 
        /// <returns> Returns Not Found if the ID is null or does not exist in the Database, otherwise returns the Index View </returns>
        public async Task<IActionResult> Edit(string id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var locations = await backend.EditAsync(id).ConfigureAwait(false);
            // If error in DB query
            if (locations == null)
            {
                return NotFound();
            }

            // If no location found
            if (locations.locations == null)
            {
                return NotFound();
            }

            return View(locations);

        }


        /// POST: Locations/Edit/5
        /// <summary>Creates the LocationsContactsSpecialQualitiesViewModel Object and attempts to insert into the Database.</summary>
        /// 
        /// <param name="id"> The string ID of a Locations Object </param>
        /// <param name="location"> The Locations Object containing the edited Location data </param>
        /// 
        /// <returns> 
        /// Returns the current View if the ID is null or if there is a Database error when attempting to insert. 
        /// If the ID isn't found in the Database, return a Not Found. Otherwise, returns Index View.
        /// </returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("LocationId," +
            "CoopLocationId," +
            "TakeCoopData," +
            "SoftDelete," +
            "Name," +
            "Address," +
            "City," +
            "County," +
            "State," +
            "PostalCode," +
            "Country," +
            "Latitude," +
            "Longitude," +

adminconsole/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BECU Console</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://unpkg.com/bootstrap-table@1.15.4/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://use.fontawesome.com/ff507f8e3b.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>

    <!--/.Navbar-->
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Locations" asp-action="Index">
                    <img class="becu_logo" src="~/media/BECU-Logo-Horizontal-rgb-01.png" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"><img class="hamburger-menu" src="~/media/hamburger-menu.png" /></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Locations" asp-action="Index">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Locations" asp-action="Create">Add Location</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Locations" asp-action="Deleted">Deleted Locations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark">Assign Privileges</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer-relative text-muted">
        <div class="container">
            &copy; 2020 - adminconsole - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
    <script src="https://unpkg.com/tableexport.jquery.plugin/libs/jsPDF/jspdf.min.js"></script>
    <script src="https://unpkg.com/tableexport.jquery.plugin/libs/jsPDF-AutoTable/jspdf.plugin.autotable.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.15.4/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.15.4/dist/extensions/export/bootstrap-table-export.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>